management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    env:
      show-values: always
    info:
      env:
        enabled: true
      java:
        enabled: true
      os:
        enabled: true
